"use client";

import { useEffect, useMemo, useState } from "react";
import { Calculator, Check, ChevronRight, CircleAlert, Clock3, Droplets, ExternalLink, Flame, Footprints, LockKeyhole, Moon, Plus, RotateCcw, Scale, ShieldCheck, Sparkles, Target, TimerReset, Trash2, TrendingDown, Trophy, Utensils, Waves } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { evidence, foods, skillLadder, type ProgramMonth } from "./fitness-data";
import { pushupVariations, pushupWeeks } from "./pushup-data";

function useStored<T>(key: string, initial: T) {
  const [value, setValue] = useState<T>(initial);
  const [ready, setReady] = useState(false);
  useEffect(() => { const raw = localStorage.getItem(key); if (raw) { try { setValue(JSON.parse(raw)); } catch {} } setReady(true); }, [key]);
  useEffect(() => { if (ready) localStorage.setItem(key, JSON.stringify(value)); }, [key, ready, value]);
  return [value, setValue] as const;
}

export function SkillsView() {
  const [done, setDone] = useStored<boolean[]>("lean-skills-v1", []);
  const completed = done.filter(Boolean).length;
  return <><div className="eyebrow">CALISTHENICS · HANDSTAND ROADMAP</div><div className="page-heading"><div><h1>Build the line first.</h1><p>Wrist capacity, shoulder control and safe exits come before freestanding attempts.</p></div><span className="safe-badge"><ShieldCheck /> No headstands</span></div><section className="skill-hero"><div><span>CURRENT LEVEL</span><h2>{skillLadder[Math.min(completed, skillLadder.length - 1)][0]}</h2><p>{skillLadder[Math.min(completed, skillLadder.length - 1)][1]}</p></div><div><strong>{completed}<small> / {skillLadder.length}</small></strong><span>milestones complete</span></div></section><div className="skill-list">{skillLadder.map(([title, test], i) => { const locked = i > completed; const complete = !!done[i]; return <article key={title} className={`skill-step ${locked ? "locked" : ""} ${complete ? "complete" : ""}`}><button disabled={locked} aria-label={`Mark ${title} complete`} onClick={() => setDone(old => old.map((v, x) => x === i ? !v : v).concat(Array(Math.max(0, i + 1 - old.length)).fill(false)).map((v, x) => x === i ? !complete : v))}>{locked ? <LockKeyhole /> : complete ? <Check /> : <span>{i + 1}</span>}</button><div><small>{complete ? "COMPLETED" : locked ? "LOCKED" : "CURRENT"}</small><h3>{title}</h3><p>Unlock test: {test}</p></div>{!locked && !complete && <ChevronRight />}</article>})}</div><aside className="info-banner"><CircleAlert /><p><b>Stop the skill session</b> for neck pain spreading into an arm, tingling, weakness, dizziness, balance change or loss of coordination. A wall hold is never worth forcing.</p></aside></>;
}

type PushupState = { baseline: number; best: number; currentWeek: number; completed: string[] };
const pushupStart: PushupState = { baseline: 0, best: 0, currentWeek: 1, completed: [] };
const unlockAt = [0, 3, 3, 10, 15, 20, 25, 30, 35, 40, 50, 60];

export function PushupView() {
  const [state, setState] = useStored<PushupState>("lean-pushups-v1", pushupStart);
  const week = pushupWeeks[state.currentWeek - 1];
  const workingVariation = state.baseline < 5 ? "Wall / high incline" : state.baseline < 10 ? "Low incline" : state.baseline < 15 ? "Knee + standard mix" : "Standard push-up";
  const completedThisWeek = week.sessions.filter((_, i) => state.completed.includes(`${week.week}-${i}`)).length;
  const setNumber = (key: "baseline" | "best", value: number) => setState(old => ({ ...old, [key]: Math.max(0, Math.round(value || 0)) }));
  return <>
    <div className="eyebrow">12-WEEK PUSH-UP MISSION · GOAL: 100 CONTINUOUS</div>
    <div className="page-heading"><div><h1>Earn every rep, in order.</h1><p>Three progressive months: first clean form, then capacity, then a carefully gated 100-rep assessment.</p></div><a className="reference-link" href="https://www.facebook.com/reel/2066590050892338" target="_blank" rel="noreferrer">Reference reel <ExternalLink /></a></div>
    <section className="pushup-hero">
      <div><Target/><span>STARTING MAX</span><label><input type="number" min="0" value={state.baseline || ""} placeholder="Test reps" onChange={e => setNumber("baseline", +e.target.value)}/> clean reps</label></div>
      <div><Trophy/><span>PERSONAL BEST</span><label><input type="number" min="0" value={state.best || ""} placeholder="Best reps" onChange={e => setNumber("best", +e.target.value)}/> clean reps</label></div>
      <div><Sparkles/><span>START WITH</span><strong>{workingVariation}</strong><small>Based on your starting max</small></div>
      <div><Clock3/><span>CURRENT BLOCK</span><strong>Week {week.week} · {week.phase}</strong><small>{completedThisWeek}/{week.sessions.length} sessions done</small></div>
    </section>
    <aside className="info-banner"><ShieldCheck/><p><b>Use this as your push training—not extra daily punishment.</b> Keep at least 48 hours between hard sessions, keep the neck neutral, and stop for radiating pain, tingling, weakness, dizziness or loss of form. Reaching 100 in 12 weeks is a goal, not a guarantee.</p></aside>
    <div className="pushup-layout">
      <section>
        <div className="section-title"><h2>Your 12-week path</h2><span>Tap a week to open it</span></div>
        <div className="week-selector">{pushupWeeks.map(item => <button key={item.week} className={item.week === week.week ? "active" : ""} onClick={() => setState(old => ({ ...old, currentWeek: item.week }))}><span>{item.week}</span><small>{item.phase}</small></button>)}</div>
        <article className="week-plan"><div className="week-plan-head"><div><span>WEEK {week.week} · {week.phase.toUpperCase()}</span><h2>{week.focus}</h2></div><b>{completedThisWeek}/{week.sessions.length}</b></div>{week.sessions.map((session, i) => { const id = `${week.week}-${i}`; const done = state.completed.includes(id); return <div className={`pushup-session ${done ? "done" : ""}`} key={id}><button className="check" aria-label={`Mark ${session.name} complete`} onClick={() => setState(old => ({ ...old, completed: done ? old.completed.filter(x => x !== id) : [...old.completed, id] }))}>{done && <Check/>}</button><div><h3>{session.name}</h3><strong>{session.prescription}</strong><p>{session.note}</p></div></div>})}{week.test && <div className="week-test"><Target/><p><b>Assessment:</b> {week.test}</p></div>}</article>
      </section>
      <aside className="variation-ladder"><div className="section-title"><h2>Variation ladder</h2><span>Do them in order</span></div>{pushupVariations.map((item, i) => { const open = state.best >= unlockAt[i] || i === 0; return <article key={item.name} className={open ? "unlocked" : "locked"}><span>{open ? <Check/> : <LockKeyhole/>}</span><div><small>{item.level}</small><h3>{item.name}</h3><p>{item.unlock}</p></div></article>})}</aside>
    </div>
  </>;
}

type FoodEntry = { id: string; name: string; multiplier: number; kcal: number; protein: number; carbs: number; fat: number; fibre: number };
export function DietView() {
  const [entries, setEntries] = useStored<FoodEntry[]>("lean-foods-v1", []);
  const [custom, setCustom] = useState({ name: "", kcal: 0, protein: 0, fibre: 0 });
  const totals = entries.reduce((a, f) => ({ kcal: a.kcal + f.kcal * f.multiplier, protein: a.protein + f.protein * f.multiplier, carbs: a.carbs + f.carbs * f.multiplier, fat: a.fat + f.fat * f.multiplier, fibre: a.fibre + f.fibre * f.multiplier }), { kcal: 0, protein: 0, carbs: 0, fat: 0, fibre: 0 });
  const add = (f: typeof foods[number]) => setEntries(e => [...e, { ...f, id: crypto.randomUUID(), multiplier: 1 }]);
  return <><div className="eyebrow">BENGALI HOME FOOD · FLEXIBLE PORTIONS</div><div className="page-heading"><div><h1>Build today’s plate.</h1><p>Approximate values for planning—not lab measurements. Measure oil separately.</p></div></div><div className="nutrition-summary"><div><span>CALORIES</span><strong>{Math.round(totals.kcal)}</strong><small>/ 1,600 kcal</small><Progress value={totals.kcal / 16} /></div><div><span>PROTEIN</span><strong>{Math.round(totals.protein)} g</strong><small>/ 110 g</small><Progress value={totals.protein / 1.1} /></div><div><span>FIBRE</span><strong>{Math.round(totals.fibre)} g</strong><small>/ 25–30 g</small><Progress value={totals.fibre / .28} /></div><div><span>CARBS · FAT</span><strong>{Math.round(totals.carbs)} · {Math.round(totals.fat)} g</strong><small>Logged estimate</small></div></div><div className="two-columns"><section><div className="section-title"><h2>Today’s food</h2><span>{entries.length} items</span></div>{entries.length === 0 && <div className="empty-state"><Utensils /><b>No food logged yet</b><p>Add a common food from the right.</p></div>}{entries.map(item => <article className="food-row" key={item.id}><div><h3>{item.name}</h3><p>{Math.round(item.kcal * item.multiplier)} kcal · {Math.round(item.protein * item.multiplier)} g protein · {Math.round(item.fibre * item.multiplier)} g fibre</p></div><label><span>Serving</span><input type="number" min="0.25" step="0.25" value={item.multiplier} onChange={e => setEntries(old => old.map(x => x.id === item.id ? { ...x, multiplier: +e.target.value } : x))} /></label><button aria-label={`Remove ${item.name}`} onClick={() => setEntries(old => old.filter(x => x.id !== item.id))}><Trash2 /></button></article>)}</section><aside className="food-library"><h2>Common foods</h2><div>{foods.map(f => <button key={f.name} onClick={() => add(f)}><span><b>{f.name}</b><small>{f.kcal} kcal · {f.protein} g protein · {f.fibre} g fibre</small></span><Plus /></button>)}</div><h3>Custom food</h3><input placeholder="Food name" value={custom.name} onChange={e => setCustom({ ...custom, name: e.target.value })} /><div className="custom-food-inputs"><input type="number" placeholder="kcal" onChange={e => setCustom({ ...custom, kcal: +e.target.value })} /><input type="number" placeholder="protein g" onChange={e => setCustom({ ...custom, protein: +e.target.value })} /><input type="number" placeholder="fibre g" onChange={e => setCustom({ ...custom, fibre: +e.target.value })} /></div><button className="secondary-button" disabled={!custom.name} onClick={() => { add({ ...custom, carbs: 0, fat: 0 }); setCustom({ name: "", kcal: 0, protein: 0, fibre: 0 }); }}>Add custom food</button></aside></div></>;
}

const mobility = [
  ["90/90 breathing", "Lie with lower legs on a chair. Breathe quietly into ribs for 5 slow breaths."],
  ["Cat–cow, small range", "Move through the upper back without throwing the head up or down."],
  ["Open-book rotation", "Keep knees stacked; rotate through the chest only as far as comfortable."],
  ["Half-kneeling hip stretch", "Gently tuck the pelvis, shift forward, keep ribs and chin level."],
  ["Wall slide", "Forearms on wall; slide upward without shrugging or pushing the chin forward."],
  ["Supported child’s pose", "Rest forearms on a chair and sit hips back with a neutral neck."],
];
export function RecoveryView() {
  const [seconds, setSeconds] = useState(300); const [running, setRunning] = useState(false);
  useEffect(() => { if (!running || seconds <= 0) return; const id = setInterval(() => setSeconds(s => s - 1), 1000); return () => clearInterval(id); }, [running, seconds]);
  const setMinutes = (m: number) => { setRunning(false); setSeconds(m * 60); };
  return <><div className="eyebrow">MOBILITY · YOGA · BREATHING</div><div className="page-heading"><div><h1>Downshift without forcing.</h1><p>Short, low-risk work for a desk-heavy day and training recovery.</p></div></div><div className="recovery-grid"><section className="breathing-card"><span>SLOW PACED BREATHING</span><div className="breath-orb"><Waves /></div><strong>{String(Math.floor(seconds / 60)).padStart(2,"0")}:{String(seconds % 60).padStart(2,"0")}</strong><p>Easy nasal inhale, longer relaxed exhale. No breath holding or forceful breathing.</p><div className="timer-presets">{[2,5,10].map(m => <button key={m} onClick={() => setMinutes(m)}>{m} min</button>)}</div><button className="primary" onClick={() => setRunning(!running)}>{running ? "Pause" : seconds === 0 ? "Restart" : "Start breathing"}</button></section><section><div className="section-title"><h2>8-minute desk reset</h2><span>Comfortable range only</span></div><div className="mobility-list">{mobility.map(([name, note], i) => <article key={name}><span>{i + 1}</span><div><h3>{name}</h3><p>{note}</p></div><small>45 sec</small></article>)}</div></section></div><aside className="info-banner"><ShieldCheck /><p>Skip headstands, shoulder stands, extreme neck positions and forceful pranayama. Yoga can support wellbeing, but it is not treatment for cervical spondylosis.</p></aside></>;
}

type Profile = { age: number; height: number; weight: number; belly: number; waist: number; activity: number; deficit: number; proteinFactor: number; water: number };
const baseProfile: Profile = { age: 30, height: 162.6, weight: 65, belly: 37, waist: 34, activity: 1.2, deficit: 300, proteinFactor: 1.7, water: 2500 };
export function CalculatorView() {
  const [p, setP] = useStored<Profile>("lean-profile-v1", baseProfile);
  const bmr = Math.round(10*p.weight + 6.25*p.height - 5*p.age + 5); const tdee = Math.round(bmr*p.activity); const target = Math.max(1500, tdee-p.deficit); const bmi = p.weight/((p.height/100)**2); const whtr = (p.belly*2.54)/p.height;
  const field = (label: string, key: keyof Profile, step="1") => <label>{label}<input type="number" step={step} value={p[key]} onChange={e => setP({ ...p, [key]: +e.target.value })} /></label>;
  return <><div className="eyebrow">PERSONAL ESTIMATES · EDITABLE INPUTS</div><div className="page-heading"><div><h1>Your numbers, with context.</h1><p>Use trends and performance—not a single calculator result—to guide changes.</p></div></div><div className="calculator-layout"><section className="form-card"><h2>Profile</h2>{field("Age", "age")}{field("Height (cm)", "height", ".1")}{field("Weight (kg)", "weight", ".1")}{field("Navel circumference (in)", "belly", ".1")} {field("Lower waist (in)", "waist", ".1")}<label>Activity estimate<select value={p.activity} onChange={e => setP({...p,activity:+e.target.value})}><option value="1.2">Sedentary · 1.2</option><option value="1.375">Light · 1.375</option><option value="1.55">Moderate · 1.55</option></select></label>{field("Daily deficit (kcal)", "deficit")}{field("Protein factor (g/kg)", "proteinFactor", ".1")}</section><section className="result-grid"><article><Calculator /><span>BMR · MIFFLIN-ST JEOR</span><strong>{bmr} kcal</strong><p>10×{p.weight} + 6.25×{p.height} − 5×{p.age} + 5</p></article><article><Flame /><span>ESTIMATED TDEE</span><strong>{tdee} kcal</strong><p>BMR × {p.activity}. Real maintenance can differ.</p></article><article><TrendingDown /><span>FAT-LOSS TARGET</span><strong>{target} kcal</strong><p>{p.deficit} kcal planned deficit; adjust only after 2 weeks of trend data.</p></article><article><Scale /><span>BMI</span><strong>{bmi.toFixed(1)}</strong><p>A screening ratio; it does not measure body fat or distribution.</p></article><article><Sparkles /><span>PROTEIN</span><strong>{Math.round(p.weight*p.proteinFactor)} g/day</strong><p>{p.proteinFactor} g/kg · editable within a practical training range.</p></article><article><TargetIcon /><span>WAIST-TO-HEIGHT</span><strong>{whtr.toFixed(2)}</strong><p>Uses navel measurement; a screening aid, not a diagnosis.</p></article></section></div><aside className="adjustment-card"><Clock3 /><div><h3>Two-week adjustment rule</h3><p>Compare 7-day average weights. If the trend is flat and adherence was strong, consider ~100–150 kcal less. If loss is fast, performance falls, or recovery is poor, add ~100–150 kcal and reassess. Never auto-cut aggressively.</p></div></aside></>;
}
function TargetIcon(){return <TrendingDown/>}

type ProgressProps = { months: ProgramMonth[]; logs: Record<string, { steps: number; water: number; sleep: number; calories: number; protein: number; weight?: number; completed: string[] }> };
export function ProgressView({ months, logs }: ProgressProps) {
  const active = months[months.length-1]; const points = active.days.map(d => ({ day:d.day, steps:logs[`${active.id}-${d.day}`]?.steps||0, weight:logs[`${active.id}-${d.day}`]?.weight })).filter(p=>p.steps||p.weight);
  const avgSteps = points.length ? Math.round(points.reduce((a,p)=>a+p.steps,0)/points.length) : 0;
  const completed = active.days.filter(d => (logs[`${active.id}-${d.day}`]?.completed.length||0)>=d.exercises.length).length;
  const max = Math.max(8000,...points.map(p=>p.steps));
  return <><div className="eyebrow">TRENDS · WEEKLY CHECKPOINTS</div><div className="page-heading"><div><h1>Read the trend, not the noise.</h1><p>Daily weight can fluctuate. Review 7-day averages every two weeks.</p></div></div><div className="progress-stats"><article><Trophy/><span>WORKOUTS</span><strong>{completed}<small>/30</small></strong></article><article><Footprints/><span>AVG STEPS</span><strong>{avgSteps.toLocaleString()}</strong></article><article><Droplets/><span>WATER LOGGED</span><strong>{points.filter(p=>logs[`${active.id}-${p.day}`]?.water).length}<small> days</small></strong></article><article><Moon/><span>7H+ SLEEP</span><strong>{active.days.filter(d=>(logs[`${active.id}-${d.day}`]?.sleep||0)>=7).length}<small> days</small></strong></article></div><section className="chart-card"><div className="section-title"><h2>Daily steps</h2><span>Target builds gradually</span></div><div className="bar-chart">{active.days.map(d => { const value=logs[`${active.id}-${d.day}`]?.steps||0; return <div key={d.day} title={`Day ${d.day}: ${value} steps`}><span style={{height:`${Math.max(2,(value/max)*100)}%`}}/><small>{d.day%5===0?d.day:""}</small></div>})}</div></section><section className="checkpoint-grid">{[7,14,21,30].map(day=><article key={day}><span>DAY {day}</span><h3>{day===30?"Month review":"Weekly checkpoint"}</h3><p>Review weight average, navel and waist, adherence, strength notes, skill level, sleep and neck symptoms.</p><button onClick={()=>window.print()}>Print review</button></article>)}</section></>;
}

export function SafetyView() {
  return <><div className="eyebrow">CERVICAL SAFE MODE · EVIDENCE</div><div className="page-heading"><div><h1>Know what to feel—and when to stop.</h1><p>This program supports training decisions. It is not medical treatment or diagnosis.</p></div></div><div className="safety-grid"><article className="normal"><Check/><h2>Normal fatigue</h2><p>Working-muscle burn, symmetrical tiredness, mild next-day soreness that settles, and effort that stops when the set ends.</p></article><article className="modify"><TimerReset/><h2>Modify today</h2><p>Local discomfort, form breaking, rising neck ache, headache, dizziness, or symptoms that worsen with a movement. Reduce range or use the listed replacement.</p></article><article className="stop"><CircleAlert/><h2>Stop + seek advice</h2><p>New or worsening arm/leg weakness, numbness or tingling, severe radiating pain, balance trouble, clumsy hands, coordination change, or bowel/bladder change.</p></article></div><section className="rules-card"><h2>Non-negotiables</h2><div>{["Keep a neutral, comfortable neck where appropriate.","Never force neck range or use jerky movements.","No neck bridges, unsupported headstands, or head-loaded inversions.","Progress wall handstands only if the overhead position is symptom-free.","When in doubt, stop and ask a qualified clinician or physiotherapist."].map(x=><p key={x}><Check/> {x}</p>)}</div></section><div className="section-title sources-title"><h2>Sources & evidence</h2><span>Open the original guidance</span></div><div className="source-grid">{evidence.map((source,i)=><a key={source.title} href={source.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,"0")}</span><div><h3>{source.title}</h3><p>{source.note}</p></div><ChevronRight/></a>)}</div></>;
}

type SettingsProps = { dark: boolean; safeMode: boolean; monthCount: number; onDark: (v:boolean)=>void; onSafe: (v:boolean)=>void; onBuildMonth:()=>void; onReset:()=>void };
export function SettingsView({dark,safeMode,monthCount,onDark,onSafe,onBuildMonth,onReset}:SettingsProps){
  return <><div className="eyebrow">PROGRAM CONTROL</div><div className="page-heading"><div><h1>Settings & future months.</h1><p>Your plan is local-first and stays on this browser.</p></div></div><div className="settings-grid"><article><div><Moon/><span><h3>Dark mode</h3><p>Use the darker training view.</p></span></div><Switch checked={dark} onCheckedChange={onDark}/></article><article><div><ShieldCheck/><span><h3>Cervical Safe Mode</h3><p>Show cautions and safe replacements.</p></span></div><Switch checked={safeMode} onCheckedChange={onSafe}/></article></div><section className="month-builder"><div><span>NEXT PHASE</span><h2>Build Month {monthCount+1}</h2><p>Creates a fresh 30-day phase from the same Push/Pull/Legs system. It carries the safety rules, raises capacity conservatively, preserves all previous logs, and ends with a deload.</p><ul><li>Same reusable exercise data model</li><li>Progressive sets, leverage and tempo—not weight alone</li><li>Step targets continue from the previous month</li><li>Separate history for every phase</li></ul></div><button className="primary" onClick={onBuildMonth}><Sparkles/> Create Month {monthCount+1}</button></section><section className="danger-zone"><div><h2>Reset all local data</h2><p>Deletes workouts, meals, skills and every generated month from this browser.</p></div><Dialog><DialogTrigger asChild><button><RotateCcw/> Reset program</button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Reset your entire program?</DialogTitle><DialogDescription>This cannot be undone. Your plan returns to Month 1, Day 1.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><button className="secondary-button">Cancel</button></DialogClose><DialogClose asChild><button className="danger-button" onClick={onReset}>Yes, reset everything</button></DialogClose></DialogFooter></DialogContent></Dialog></section></>;
}
