"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Calculator, Check, ChevronRight, CircleAlert, Clock3, Droplets, Dumbbell, ExternalLink, Flame, Footprints, LockKeyhole, Moon, Plus, RotateCcw, Scale, ShieldCheck, Sparkles, Target, TimerReset, Trash2, TrendingDown, Trophy, Utensils, Waves, X } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { evidence, foods, skillLadder, type ProgramMonth } from "./fitness-data";
import { pushupVariations, pushupWeeks, reelVariations } from "./pushup-data";

function useStored<T>(key: string, initial: T) {
  const [value, setValue] = useState<T>(initial);
  const [ready, setReady] = useState(false);
  useEffect(() => { const raw = localStorage.getItem(key); if (raw) { try { setValue(JSON.parse(raw)); } catch {} } setReady(true); }, [key]);
  useEffect(() => { if (ready) localStorage.setItem(key, JSON.stringify(value)); }, [key, ready, value]);
  return [value, setValue] as const;
}

export function SkillsView() {
  const [done, setDone] = useStored<boolean[]>("lean-skills-v1", []);
  const completed = done.filter(Boolean).length;
  return <><div className="eyebrow">CALISTHENICS · HANDSTAND ROADMAP</div><div className="page-heading"><div><h1>Build the line first.</h1><p>Wrist capacity, shoulder control and safe exits come before freestanding attempts.</p></div><span className="safe-badge"><ShieldCheck /> No headstands</span></div><section className="skill-hero"><div><span>CURRENT LEVEL</span><h2>{skillLadder[Math.min(completed, skillLadder.length - 1)][0]}</h2><p>{skillLadder[Math.min(completed, skillLadder.length - 1)][1]}</p></div><div><strong>{completed}<small> / {skillLadder.length}</small></strong><span>milestones complete</span></div></section><div className="skill-list">{skillLadder.map(([title, test], i) => { const locked = i > completed; const complete = !!done[i]; return <article key={title} className={`skill-step ${locked ? "locked" : ""} ${complete ? "complete" : ""}`}><button disabled={locked} aria-label={`Mark ${title} complete`} onClick={() => setDone(old => old.map((v, x) => x === i ? !v : v).concat(Array(Math.max(0, i + 1 - old.length)).fill(false)).map((v, x) => x === i ? !complete : v))}>{locked ? <LockKeyhole /> : complete ? <Check /> : <span>{i + 1}</span>}</button><div><small>{complete ? "COMPLETED" : locked ? "LOCKED" : "CURRENT"}</small><h3>{title}</h3><p>Unlock test: {test}</p></div>{!locked && !complete && <ChevronRight />}</article>})}</div><aside className="info-banner"><CircleAlert /><p><b>Stop the skill session</b> for neck pain spreading into an arm, tingling, weakness, dizziness, balance change or loss of coordination. A wall hold is never worth forcing.</p></aside></>;
}

type PushupState = { baseline: number; best: number; currentWeek: number; completed: string[]; variationDone: string[]; variationReps: Record<string, string> };
const pushupStart: PushupState = { baseline: 0, best: 0, currentWeek: 1, completed: [], variationDone: [], variationReps: {} };
const unlockAt = [0, 3, 3, 10, 15, 20, 25, 30, 35, 40, 50, 60];

export function PushupView() {
  const [state, setState] = useStored<PushupState>("lean-pushups-v1", pushupStart);
  const week = pushupWeeks[state.currentWeek - 1];
  const variationDone = state.variationDone ?? [];
  const variationReps = state.variationReps ?? {};
  const workingVariation = state.baseline < 5 ? "Wall / high incline" : state.baseline < 10 ? "Low incline" : state.baseline < 15 ? "Knee + standard mix" : "Standard push-up";
  const completedThisWeek = week.sessions.filter((_, i) => state.completed.includes(`${week.week}-${i}`)).length;
  const reelDone = reelVariations.filter(item => variationDone.includes(item.id)).length;
  const setNumber = (key: "baseline" | "best", value: number) => setState(old => ({ ...old, [key]: Math.max(0, Math.round(value || 0)) }));
  return <>
    <div className="eyebrow">12-WEEK PUSH-UP MISSION · GOAL: 100 CONTINUOUS</div>
    <div className="page-heading"><div><h1>Earn every rep, in order.</h1><p>Three progressive months: first clean form, then capacity, then a carefully gated 100-rep assessment.</p></div><a className="reference-link" href="https://www.facebook.com/reel/2066590050892338" target="_blank" rel="noreferrer">Reference reel <ExternalLink /></a></div>
    <section className="pushup-hero">
      <div><Target/><span>STARTING MAX</span><label><input type="number" min="0" value={state.baseline || ""} placeholder="Test reps" onChange={e => setNumber("baseline", +e.target.value)}/> clean reps</label></div>
      <div><Trophy/><span>PERSONAL BEST</span><label><input type="number" min="0" value={state.best || ""} placeholder="Best reps" onChange={e => setNumber("best", +e.target.value)}/> clean reps</label></div>
      <div><Sparkles/><span>START WITH</span><strong>{workingVariation}</strong><small>Based on your starting max</small></div>
      <div><Clock3/><span>CURRENT BLOCK</span><strong>Week {week.week} · {week.phase}</strong><small>{completedThisWeek}/{week.sessions.length} sessions done</small></div>
    </section>
    <aside className="info-banner"><ShieldCheck/><p><b>Use this as your push training—not extra daily punishment.</b> Keep at least 48 hours between hard sessions, keep the neck neutral, and stop for radiating pain, tingling, weakness, dizziness or loss of form. Reaching 100 in 12 weeks is a goal, not a guarantee.</p></aside>
    <section className="reel-circuit">
      <div className="section-title"><div><span className="reel-label">REFERENCE-SEQUENCE SKILLS</span><h2>Seven variations from your screenshots</h2></div><strong>{reelDone}/{reelVariations.length} learned</strong></div>
      <p className="reel-intro">The reel counts are technique samples, not a workout prescription. Unlock the variation in its listed week, practise it fresh, and record only clean reps.</p>
      <div className="reel-variation-grid">{reelVariations.map((item, i) => { const done = variationDone.includes(item.id); const available = state.currentWeek >= item.startWeek; return <article key={item.id} className={`${done ? "done" : ""} ${available ? "available" : "locked"}`}><div className="variation-top"><span>{String(i + 1).padStart(2, "0")}</span><small>FROM WEEK {item.startWeek}</small><button disabled={!available} aria-label={`Mark ${item.name} learned`} onClick={() => setState(old => ({ ...old, variationDone: done ? (old.variationDone ?? []).filter(x => x !== item.id) : [...(old.variationDone ?? []), item.id] }))}>{available ? done ? <Check/> : "Mark" : <LockKeyhole/>}</button></div><h3>{item.name}</h3><b>{item.focus}</b><p>{item.cue}</p><div className="variation-log"><span>Reel: {item.reelTarget}</span><label>My clean reps <input inputMode="numeric" value={variationReps[item.id] ?? ""} placeholder="0" onChange={e => setState(old => ({ ...old, variationReps: { ...(old.variationReps ?? {}), [item.id]: e.target.value } }))}/></label></div><small className="variation-safety"><ShieldCheck/> {item.safety}</small></article>})}</div>
    </section>
    <div className="pushup-layout">
      <section>
        <div className="section-title"><h2>Your 12-week path</h2><span>Tap a week to open it</span></div>
        <div className="week-selector">{pushupWeeks.map(item => <button key={item.week} className={item.week === week.week ? "active" : ""} onClick={() => setState(old => ({ ...old, currentWeek: item.week }))}><span>{item.week}</span><small>{item.phase}</small></button>)}</div>
        <article className="week-plan"><div className="week-plan-head"><div><span>WEEK {week.week} · {week.phase.toUpperCase()}</span><h2>{week.focus}</h2></div><b>{completedThisWeek}/{week.sessions.length}</b></div>{week.sessions.map((session, i) => { const id = `${week.week}-${i}`; const done = state.completed.includes(id); return <div className={`pushup-session ${done ? "done" : ""}`} key={id}><button className="check" aria-label={`Mark ${session.name} complete`} onClick={() => setState(old => ({ ...old, completed: done ? old.completed.filter(x => x !== id) : [...old.completed, id] }))}>{done && <Check/>}</button><div><h3>{session.name}</h3><strong>{session.prescription}</strong><p>{session.note}</p></div></div>})}{week.test && <div className="week-test"><Target/><p><b>Assessment:</b> {week.test}</p></div>}</article>
      </section>
      <aside className="variation-ladder"><div className="section-title"><h2>Variation ladder</h2><span>Do them in order</span></div>{pushupVariations.map((item, i) => { const open = state.best >= unlockAt[i] || i === 0; return <article key={item.name} className={open ? "unlocked" : "locked"}><span>{open ? <Check/> : <LockKeyhole/>}</span><div><small>{item.level}</small><h3>{item.name}</h3><p>{item.unlock}</p></div></article>})}</aside>
    </div>
  </>;
}

type FoodEntry = { id: string; name: string; multiplier: number; kcal: number; protein: number; carbs: number; fat: number; fibre: number };
export function DietView() {
  const [entries, setEntries] = useStored<FoodEntry[]>("lean-foods-v1", []);
  const [custom, setCustom] = useState({ name: "", kcal: 0, protein: 0, fibre: 0 });
  const totals = entries.reduce((a, f) => ({ kcal: a.kcal + f.kcal * f.multiplier, protein: a.protein + f.protein * f.multiplier, carbs: a.carbs + f.carbs * f.multiplier, fat: a.fat + f.fat * f.multiplier, fibre: a.fibre + f.fibre * f.multiplier }), { kcal: 0, protein: 0, carbs: 0, fat: 0, fibre: 0 });
  const add = (f: typeof foods[number]) => setEntries(e => [...e, { ...f, id: crypto.randomUUID(), multiplier: 1 }]);
  return <><div className="eyebrow">BENGALI HOME FOOD · FLEXIBLE PORTIONS</div><div className="page-heading"><div><h1>Build today’s plate.</h1><p>Approximate values for planning—not lab measurements. Measure oil separately.</p></div></div><div className="nutrition-summary"><div><span>CALORIES</span><strong>{Math.round(totals.kcal)}</strong><small>/ 1,600 kcal</small><Progress value={totals.kcal / 16} /></div><div><span>PROTEIN</span><strong>{Math.round(totals.protein)} g</strong><small>/ 110 g</small><Progress value={totals.protein / 1.1} /></div><div><span>FIBRE</span><strong>{Math.round(totals.fibre)} g</strong><small>/ 25–30 g</small><Progress value={totals.fibre / .28} /></div><div><span>CARBS · FAT</span><strong>{Math.round(totals.carbs)} · {Math.round(totals.fat)} g</strong><small>Logged estimate</small></div></div><div className="two-columns"><section><div className="section-title"><h2>Today’s food</h2><span>{entries.length} items</span></div>{entries.length === 0 && <div className="empty-state"><Utensils /><b>No food logged yet</b><p>Add a common food from the right.</p></div>}{entries.map(item => <article className="food-row" key={item.id}><div><h3>{item.name}</h3><p>{Math.round(item.kcal * item.multiplier)} kcal · {Math.round(item.protein * item.multiplier)} g protein · {Math.round(item.fibre * item.multiplier)} g fibre</p></div><label><span>Serving</span><input type="number" min="0.25" step="0.25" value={item.multiplier} onChange={e => setEntries(old => old.map(x => x.id === item.id ? { ...x, multiplier: +e.target.value } : x))} /></label><button aria-label={`Remove ${item.name}`} onClick={() => setEntries(old => old.filter(x => x.id !== item.id))}><Trash2 /></button></article>)}</section><aside className="food-library"><h2>Common foods</h2><div>{foods.map(f => <button key={f.name} onClick={() => add(f)}><span><b>{f.name}</b><small>{f.kcal} kcal · {f.protein} g protein · {f.fibre} g fibre</small></span><Plus /></button>)}</div><h3>Custom food</h3><input placeholder="Food name" value={custom.name} onChange={e => setCustom({ ...custom, name: e.target.value })} /><div className="custom-food-inputs"><input type="number" placeholder="kcal" onChange={e => setCustom({ ...custom, kcal: +e.target.value })} /><input type="number" placeholder="protein g" onChange={e => setCustom({ ...custom, protein: +e.target.value })} /><input type="number" placeholder="fibre g" onChange={e => setCustom({ ...custom, fibre: +e.target.value })} /></div><button className="secondary-button" disabled={!custom.name} onClick={() => { add({ ...custom, carbs: 0, fat: 0 }); setCustom({ name: "", kcal: 0, protein: 0, fibre: 0 }); }}>Add custom food</button></aside></div></>;
}

const mobility = [
  ["90/90 breathing", "Lie with lower legs on a chair. Breathe quietly into ribs for 5 slow breaths."],
  ["Cat–cow, small range", "Move through the upper back without throwing the head up or down."],
  ["Open-book rotation", "Keep knees stacked; rotate through the chest only as far as comfortable."],
  ["Half-kneeling hip stretch", "Gently tuck the pelvis, shift forward, keep ribs and chin level."],
  ["Wall slide", "Forearms on wall; slide upward without shrugging or pushing the chin forward."],
  ["Supported child’s pose", "Rest forearms on a chair and sit hips back with a neutral neck."],
];
export function RecoveryView() {
  const [seconds, setSeconds] = useState(300); const [running, setRunning] = useState(false);
  useEffect(() => { if (!running || seconds <= 0) return; const id = setInterval(() => setSeconds(s => s - 1), 1000); return () => clearInterval(id); }, [running, seconds]);
  const setMinutes = (m: number) => { setRunning(false); setSeconds(m * 60); };
  return <><div className="eyebrow">MOBILITY · YOGA · BREATHING</div><div className="page-heading"><div><h1>Downshift without forcing.</h1><p>Short, low-risk work for a desk-heavy day and training recovery.</p></div></div><div className="recovery-grid"><section className="breathing-card"><span>SLOW PACED BREATHING</span><div className="breath-orb"><Waves /></div><strong>{String(Math.floor(seconds / 60)).padStart(2,"0")}:{String(seconds % 60).padStart(2,"0")}</strong><p>Easy nasal inhale, longer relaxed exhale. No breath holding or forceful breathing.</p><div className="timer-presets">{[2,5,10].map(m => <button key={m} onClick={() => setMinutes(m)}>{m} min</button>)}</div><button className="primary" onClick={() => setRunning(!running)}>{running ? "Pause" : seconds === 0 ? "Restart" : "Start breathing"}</button></section><section><div className="section-title"><h2>8-minute desk reset</h2><span>Comfortable range only</span></div><div className="mobility-list">{mobility.map(([name, note], i) => <article key={name}><span>{i + 1}</span><div><h3>{name}</h3><p>{note}</p></div><small>45 sec</small></article>)}</div></section></div><aside className="info-banner"><ShieldCheck /><p>Skip headstands, shoulder stands, extreme neck positions and forceful pranayama. Yoga can support wellbeing, but it is not treatment for cervical spondylosis.</p></aside></>;
}

type Profile = { age: number; height: number; weight: number; belly: number; waist: number; activity: number; deficit: number; proteinFactor: number; water: number };
const baseProfile: Profile = { age: 30, height: 162.6, weight: 65, belly: 37, waist: 34, activity: 1.2, deficit: 300, proteinFactor: 1.7, water: 2500 };
export function CalculatorView() {
  const [p, setP] = useStored<Profile>("lean-profile-v1", baseProfile);
  const bmr = Math.round(10*p.weight + 6.25*p.height - 5*p.age + 5); const tdee = Math.round(bmr*p.activity); const target = Math.max(1500, tdee-p.deficit); const bmi = p.weight/((p.height/100)**2); const whtr = (p.belly*2.54)/p.height;
  const field = (label: string, key: keyof Profile, step="1") => <label>{label}<input type="number" step={step} value={p[key]} onChange={e => setP({ ...p, [key]: +e.target.value })} /></label>;
  return <><div className="eyebrow">PERSONAL ESTIMATES · EDITABLE INPUTS</div><div className="page-heading"><div><h1>Your numbers, with context.</h1><p>Use trends and performance—not a single calculator result—to guide changes.</p></div></div><div className="calculator-layout"><section className="form-card"><h2>Profile</h2>{field("Age", "age")}{field("Height (cm)", "height", ".1")}{field("Weight (kg)", "weight", ".1")}{field("Navel circumference (in)", "belly", ".1")} {field("Lower waist (in)", "waist", ".1")}<label>Activity estimate<select value={p.activity} onChange={e => setP({...p,activity:+e.target.value})}><option value="1.2">Sedentary · 1.2</option><option value="1.375">Light · 1.375</option><option value="1.55">Moderate · 1.55</option></select></label>{field("Daily deficit (kcal)", "deficit")}{field("Protein factor (g/kg)", "proteinFactor", ".1")}</section><section className="result-grid"><article><Calculator /><span>BMR · MIFFLIN-ST JEOR</span><strong>{bmr} kcal</strong><p>10×{p.weight} + 6.25×{p.height} − 5×{p.age} + 5</p></article><article><Flame /><span>ESTIMATED TDEE</span><strong>{tdee} kcal</strong><p>BMR × {p.activity}. Real maintenance can differ.</p></article><article><TrendingDown /><span>FAT-LOSS TARGET</span><strong>{target} kcal</strong><p>{p.deficit} kcal planned deficit; adjust only after 2 weeks of trend data.</p></article><article><Scale /><span>BMI</span><strong>{bmi.toFixed(1)}</strong><p>A screening ratio; it does not measure body fat or distribution.</p></article><article><Sparkles /><span>PROTEIN</span><strong>{Math.round(p.weight*p.proteinFactor)} g/day</strong><p>{p.proteinFactor} g/kg · editable within a practical training range.</p></article><article><TargetIcon /><span>WAIST-TO-HEIGHT</span><strong>{whtr.toFixed(2)}</strong><p>Uses navel measurement; a screening aid, not a diagnosis.</p></article></section></div><aside className="adjustment-card"><Clock3 /><div><h3>Two-week adjustment rule</h3><p>Compare 7-day average weights. If the trend is flat and adherence was strong, consider ~100–150 kcal less. If loss is fast, performance falls, or recovery is poor, add ~100–150 kcal and reassess. Never auto-cut aggressively.</p></div></aside></>;
}
function TargetIcon(){return <TrendingDown/>}

type ProgressProps = { months: ProgramMonth[]; logs: Record<string, { steps: number; water: number; sleep: number; calories: number; protein: number; weight?: number; completed: string[] }> };
export function ProgressView({ months, logs }: ProgressProps) {
  const active = months[months.length-1]; const points = active.days.map(d => ({ day:d.day, steps:logs[`${active.id}-${d.day}`]?.steps||0, weight:logs[`${active.id}-${d.day}`]?.weight })).filter(p=>p.steps||p.weight);
  const avgSteps = points.length ? Math.round(points.reduce((a,p)=>a+p.steps,0)/points.length) : 0;
  const completed = active.days.filter(d => (logs[`${active.id}-${d.day}`]?.completed.length||0)>=d.exercises.length).length;
  const max = Math.max(8000,...points.map(p=>p.steps));
  return <><div className="eyebrow">TRENDS · WEEKLY CHECKPOINTS</div><div className="page-heading"><div><h1>Read the trend, not the noise.</h1><p>Daily weight can fluctuate. Review 7-day averages every two weeks.</p></div></div><div className="progress-stats"><article><Trophy/><span>WORKOUTS</span><strong>{completed}<small>/30</small></strong></article><article><Footprints/><span>AVG STEPS</span><strong>{avgSteps.toLocaleString()}</strong></article><article><Droplets/><span>WATER LOGGED</span><strong>{points.filter(p=>logs[`${active.id}-${p.day}`]?.water).length}<small> days</small></strong></article><article><Moon/><span>7H+ SLEEP</span><strong>{active.days.filter(d=>(logs[`${active.id}-${d.day}`]?.sleep||0)>=7).length}<small> days</small></strong></article></div><section className="chart-card"><div className="section-title"><h2>Daily steps</h2><span>Target builds gradually</span></div><div className="bar-chart">{active.days.map(d => { const value=logs[`${active.id}-${d.day}`]?.steps||0; return <div key={d.day} title={`Day ${d.day}: ${value} steps`}><span style={{height:`${Math.max(2,(value/max)*100)}%`}}/><small>{d.day%5===0?d.day:""}</small></div>})}</div></section><section className="checkpoint-grid">{[7,14,21,30].map(day=><article key={day}><span>DAY {day}</span><h3>{day===30?"Month review":"Weekly checkpoint"}</h3><p>Review weight average, navel and waist, adherence, strength notes, skill level, sleep and neck symptoms.</p><button onClick={()=>window.print()}>Print review</button></article>)}</section></>;
}

export function SafetyView() {
  return <><div className="eyebrow">CERVICAL SAFE MODE · EVIDENCE</div><div className="page-heading"><div><h1>Know what to feel—and when to stop.</h1><p>This program supports training decisions. It is not medical treatment or diagnosis.</p></div></div><div className="safety-grid"><article className="normal"><Check/><h2>Normal fatigue</h2><p>Working-muscle burn, symmetrical tiredness, mild next-day soreness that settles, and effort that stops when the set ends.</p></article><article className="modify"><TimerReset/><h2>Modify today</h2><p>Local discomfort, form breaking, rising neck ache, headache, dizziness, or symptoms that worsen with a movement. Reduce range or use the listed replacement.</p></article><article className="stop"><CircleAlert/><h2>Stop + seek advice</h2><p>New or worsening arm/leg weakness, numbness or tingling, severe radiating pain, balance trouble, clumsy hands, coordination change, or bowel/bladder change.</p></article></div><section className="rules-card"><h2>Non-negotiables</h2><div>{["Keep a neutral, comfortable neck where appropriate.","Never force neck range or use jerky movements.","No neck bridges, unsupported headstands, or head-loaded inversions.","Progress wall handstands only if the overhead position is symptom-free.","When in doubt, stop and ask a qualified clinician or physiotherapist."].map(x=><p key={x}><Check/> {x}</p>)}</div></section><div className="section-title sources-title"><h2>Sources & evidence</h2><span>Open the original guidance</span></div><div className="source-grid">{evidence.map((source,i)=><a key={source.title} href={source.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,"0")}</span><div><h3>{source.title}</h3><p>{source.note}</p></div><ChevronRight/></a>)}</div></>;
}

type SettingsProps = { dark: boolean; safeMode: boolean; monthCount: number; onDark: (v:boolean)=>void; onSafe: (v:boolean)=>void; onBuildMonth:()=>void; onReset:()=>void };
export function SettingsView({dark,safeMode,monthCount,onDark,onSafe,onBuildMonth,onReset}:SettingsProps){
  return <><div className="eyebrow">PROGRAM CONTROL</div><div className="page-heading"><div><h1>Settings & future months.</h1><p>Your plan is local-first and stays on this browser.</p></div></div><div className="settings-grid"><article><div><Moon/><span><h3>Dark mode</h3><p>Use the darker training view.</p></span></div><Switch checked={dark} onCheckedChange={onDark}/></article><article><div><ShieldCheck/><span><h3>Cervical Safe Mode</h3><p>Show cautions and safe replacements.</p></span></div><Switch checked={safeMode} onCheckedChange={onSafe}/></article></div><section className="month-builder"><div><span>NEXT PHASE</span><h2>Build Month {monthCount+1}</h2><p>Creates a fresh 30-day phase from the same Push/Pull/Legs system. It carries the safety rules, raises capacity conservatively, preserves all previous logs, and ends with a deload.</p><ul><li>Same reusable exercise data model</li><li>Progressive sets, leverage and tempo—not weight alone</li><li>Step targets continue from the previous month</li><li>Separate history for every phase</li></ul></div><button className="primary" onClick={onBuildMonth}><Sparkles/> Create Month {monthCount+1}</button></section><section className="danger-zone"><div><h2>Reset all local data</h2><p>Deletes workouts, meals, skills and every generated month from this browser.</p></div><Dialog><DialogTrigger asChild><button><RotateCcw/> Reset program</button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Reset your entire program?</DialogTitle><DialogDescription>This cannot be undone. Your plan returns to Month 1, Day 1.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><button className="secondary-button">Cancel</button></DialogClose><DialogClose asChild><button className="danger-button" onClick={onReset}>Yes, reset everything</button></DialogClose></DialogFooter></DialogContent></Dialog></section></>;
}

type PlanMode = "template" | "custom";
type CustomPlan = { id: string; name: string; duration: 1 | 2 | 3; startDate: string; mode: PlanMode; template?: string; schedule: string[][]; createdAt: string };
const planTemplates = [
  ["ppl-bodyweight", "Push · Pull · Legs — Bodyweight", "No equipment · strength foundation"],
  ["ppl-dumbbell", "Push · Pull · Legs — Dumbbells", "Dumbbells · balanced strength"],
  ["fat-loss", "Fat-loss foundation", "Strength, steps and cardio"],
  ["calisthenics", "Calisthenics mastery", "Skills, strength and control"],
  ["pushup", "Push-up mastery", "Progress toward one high-rep set"],
] as const;
const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const focusOptions = ["Rest / recovery", "Full upper body", "Chest", "Back", "Shoulders", "Arms", "Forearms", "Core", "Full lower body", "Quads", "Hamstrings", "Glutes", "Calves", "Full body", "Cardio", "Stretching"];
const defaultSchedule = [["Full upper body"], ["Full lower body"], ["Cardio"], ["Back"], ["Chest"], ["Full body"], ["Rest / recovery"]];

function usePlans() { return useStored<CustomPlan[]>("lean-created-plans-v1", []); }
function formatDate(date: string) { return date ? new Intl.DateTimeFormat("en", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${date}T00:00:00`)) : "Start date not set"; }

export function YourPlansView({ onCreate }: { onCreate: () => void }) {
  const [plans, setPlans] = usePlans();
  return <><div className="eyebrow">YOUR TRAINING LIBRARY</div><div className="page-heading"><div><h1>Your plans.</h1><p>Create up to three months at a time. Each plan starts on the date you choose.</p></div><button className="primary" onClick={onCreate}><Plus /> Create plan</button></div>{plans.length === 0 ? <section className="plans-empty"><Dumbbell /><h2>Your first plan starts here.</h2><p>Choose a proven template or map your own weekly muscle split. Exercises come in the next step.</p><button className="primary" onClick={onCreate}>Create a plan <ChevronRight /></button></section> : <div className="created-plan-list">{plans.map(plan => <article key={plan.id}><div className="plan-card-icon"><CalendarDays /></div><div><span>{plan.mode === "template" ? "PRE-BUILT PLAN" : "CUSTOM WEEKLY SPLIT"}</span><h2>{plan.name}</h2><p>Starts {formatDate(plan.startDate)} · {plan.duration} {plan.duration === 1 ? "month" : "months"}</p><div className="plan-mini-schedule">{plan.schedule.map((focus, i) => <small key={`${plan.id}-${i}`}><b>{weekdays[i].slice(0, 3)}</b><em>{(Array.isArray(focus) ? focus : [focus]).join(" · ")}</em></small>)}</div></div><button className="delete-plan" aria-label={`Delete ${plan.name}`} onClick={() => setPlans(current => current.filter(item => item.id !== plan.id))}><Trash2 /></button></article>)}</div>}</>;
}

export function CreatePlanView({ onCreated }: { onCreated: () => void }) {
  const [, setPlans] = usePlans();
  const [mode, setMode] = useState<PlanMode>("template");
  const [duration, setDuration] = useState<1 | 2 | 3>(1);
  const [startDate, setStartDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [template, setTemplate] = useState<string>(planTemplates[0][0]);
  const [name, setName] = useState("");
  const [schedule, setSchedule] = useState(defaultSchedule);
  const selectedTemplate = planTemplates.find(item => item[0] === template)!;
  const save = () => {
    const plan: CustomPlan = { id: crypto.randomUUID(), name: name.trim() || (mode === "template" ? selectedTemplate[1] : "My custom training plan"), duration, startDate, mode, template: mode === "template" ? template : undefined, schedule: mode === "template" ? [["Push"], ["Pull"], ["Legs"], ["Recovery"], ["Push"], ["Pull"], ["Rest"]] : schedule, createdAt: new Date().toISOString() };
    setPlans(current => [plan, ...current]); onCreated();
  };
  const addFocus = (dayIndex: number, focus: string) => { if (!focus || schedule[dayIndex].includes(focus)) return; setSchedule(current => current.map((day, index) => index === dayIndex ? [...day, focus] : day)); };
  const removeFocus = (dayIndex: number, focus: string) => setSchedule(current => current.map((day, index) => index === dayIndex ? day.filter(item => item !== focus) : day));
  return <><div className="eyebrow">PLAN BUILDER · STEP 1 OF 2</div><div className="page-heading"><div><h1>Create a training plan.</h1><p>First choose the calendar and weekly structure. We&apos;ll add the exact exercises inside each day next.</p></div></div><section className="plan-builder"><div className="plan-mode-toggle"><button className={mode === "template" ? "active" : ""} onClick={() => setMode("template")}><Sparkles /><span><b>Use a pre-built plan</b><small>Start from a proven structure</small></span></button><button className={mode === "custom" ? "active" : ""} onClick={() => setMode("custom")}><CalendarDays /><span><b>Customize my week</b><small>Choose the muscle focus for every day</small></span></button></div><div className="plan-basics"><label>Plan name <input value={name} onChange={e => setName(e.target.value)} placeholder={mode === "template" ? selectedTemplate[1] : "e.g. My strength block"} /></label><label>Duration <select value={duration} onChange={e => setDuration(+e.target.value as 1 | 2 | 3)}><option value="1">1 month</option><option value="2">2 months</option><option value="3">3 months</option></select></label><label>Start date <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} /></label></div>{mode === "template" ? <div className="template-picker"><h2>Choose a plan type</h2><p>Each one gives you a ready-made weekly rhythm. You can tune exercises later.</p><div>{planTemplates.map(item => <button key={item[0]} className={template === item[0] ? "selected" : ""} onClick={() => setTemplate(item[0])}><span><b>{item[1]}</b><small>{item[2]}</small></span>{template === item[0] && <Check />}</button>)}</div></div> : <div className="weekly-customizer"><div className="section-title"><div><h2>Build your weekly split</h2><span>Add one or more muscle focuses to a day</span></div></div>{weekdays.map((day, index) => <div className="custom-day" key={day}><b>{day}</b><div><div className="focus-tags">{schedule[index].map(focus => <span key={focus}>{focus}<button aria-label={`Remove ${focus} from ${day}`} onClick={() => removeFocus(index, focus)}><X /></button></span>)}</div><div className="focus-add"><select defaultValue=""><option value="" disabled>Select focus</option>{focusOptions.filter(focus => !schedule[index].includes(focus)).map(focus => <option key={focus}>{focus}</option>)}</select><button onClick={event => { const select = event.currentTarget.previousElementSibling as HTMLSelectElement; addFocus(index, select.value); select.value = ""; }}><Plus /> Add</button></div></div></div>)}</div>}<div className="plan-builder-footer"><span><CalendarDays /> Starts {formatDate(startDate)} · {duration} {duration === 1 ? "month" : "months"}</span><button className="primary" onClick={save}>Create plan <ChevronRight /></button></div></section></>;
}
